### PR TITLE
Weather station 1.2

### PR DESCRIPTION
**Pull request by fogdingding**
add new station_name in the Hsinchu City， that station_name is Siangshan (C0D570)。

### CODE REVIEW

**Comment by peter279k** [comment]
@fogdingding, thank you for your reply.
If possible, please add the English comment and let others can understand easily :+1: .

**Comment by fogdingding** [comment]
ok,i will

**Comment by peter279k** [comment]
@fogdingding, you can use the `edited` pen to edit the previous comment you write.

image

Thanks.

**Comment by fogdingding** [comment]
OK，done。

**Comment by peter279k** [comment]
This PR will be merged and don't forget some tips I suggest that you need to consider :+1: .

**Pull request merged**
